// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzjqyngsbmeflkqenbjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6anF5bmdzYm1lZmxrcWVuYmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjcxNjAsImV4cCI6MjA3NDMwMzE2MH0.HxQDL25Gb18efqtmplWEBhAs2CFeSuoildtoImVsg2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});